name: Deploy Container Apps

pool:
  vmImage: ubuntu-latest

trigger:
  - none

stages:
  - stage: Validate
    displayName: Manual validation
    jobs:
      - job: A
        steps:
          - script: echo hello from the Debug build
      - job: B
        dependsOn: A
        steps:
          - script: echo hello from the Release build